##Fancy Indexing
you can Pick elements from specific positions using a list/array of indices.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])



arr[[0,2,5]]

array([1, 3, 6])

You can do this fancy indexing in 2D Matrix aswell

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

matrix[[0,2],[1,2]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 9])

##Conditional Selection
Find values based on conditions or replace them.

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

arr[arr>3]
np.where(arr>3)
np.where(arr>3,arr,0)

array([ 0,  0,  0,  4,  5,  6,  7,  8,  9, 10])

##Sorting & Ordering
np.sort() → returns sorted array

np.argsort() → returns indices of sorted order

In [ ]:
arr = np.array([5,42,1,3,55,49])

np.sort(arr)
np.argsort(arr)

array([2, 3, 0, 1, 5, 4])

##Concatenation & Stacking

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

Vertical & Horizontal Stacking

In [19]:
arr1 = np.array([[1,2,3],[4,5,6]])



In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2 = np.array([[7,8,9],[10,11,12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])