##1. Attributes of an Array

Introduce attributes that describe the array.

Attributes: .shape, .ndim, .size, .dtype.

In [6]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)

(2, 3)
2
6
int64


##Indexing and Slicing
Now we have Indexing and slicing aswell and for that we are going to see 1d and 2d indexing lets start with **1D indexing** and it is similar to list.

In [7]:
arr = np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[1])


1
2


Now lets see the 2D indexing aswell

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[1,1])

5


Now we can also do the slicing lets see the **slicing in 1D**

In [13]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:4])
print(arr[1:4:2])
print(arr[::2])

[2 3 4]
[2 4]
[1 3 5]


1D slicing was really easy now lets see the **slicing in 2D**

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1,1:3])
print(arr[0:2,2])
print(arr[0:2,1:4])

[5 6]
[3 6]
[[2 3]
 [5 6]]


There is one more thing known as **Boolean indexing**

In [19]:
arr = np.array([1,2,3,4,5,6])
print(arr>2)

print(arr[arr>2])

[False False  True  True  True  True]
[3 4 5 6]


In [20]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr>2)

print(arr[arr>2])

[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[3 4 5 6 7 8 9]


## Reshaping the Array

you can also reshape the Array as you like but be accurate about the dimensions

In [21]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Flattening of an array

you can convert the 2D array to 1D using the Flattening Function

In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])